apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  #type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: schema-registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: schema-registry
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - image: confluentinc/cp-schema-registry:3.2.1
        name: schema-registry
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://schema-registry:8081