---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  #type: LoadBalancer
  ports:
    - port: 8081
      #targetPort: 8081
      #protocol: TCP
  clusterIP: None
  selector:
    app: schema-registry
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: registry
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - image: confluentinc/cp-schema-registry:latest
        name: schema-registry
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry-0.schema-registry.default.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
