---
apiVersion: v1
kind: Service
metadata:
  name: schema
spec:
  #type: LoadBalancer
  ports:
    - port: 8081
      #targetPort: 8081
      #protocol: TCP
  clusterIP: None
  selector:
    app: schema-registry
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: "schema"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:latest
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry-0.schema.default.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081
