---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  #type: LoadBalancer
  ports:
    - port: 3606
      targetPort: 3606
      protocol: TCP
  #clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1beta1
kind: deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: confluent
        - name: MYSQL_USER
          value: confluent
        - name: MYSQL_PASSWORD
          value: confluent
        - name: MYSQL_DATABASE
          value: confluent_test
        ports:
        - containerPort: 3606